name: "PR Checks"
# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.4
          architecture: x64
      - name: Install flake8
        run: pip install flake8
        with:
          checkName: 'check_pr'   # NOTE: this needs to be the same as the job name
