name: "PR Checks"
# Triggers the workflow on push or pull request events
on: pull_request

jobs:
  pr_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.9
          architecture: x64

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Running Tox
        run: tox

      - name: Running flake8
        run: flake8
